name: t_store_ecommerce_app
description: "A new Flutter project."


publish_to: 'none' 




version: 1.0.0+1

environment:
  sdk: ^3.5.4



dependencies:
  flutter:
    sdk: flutter


  #---------------- ./ PACKAGES START ------------------#

  # Utility Packages
  http: ^1.2.2
  logger: ^2.5.0
  url_launcher: ^6.3.1
  intl: ^0.20.2

  # Icons
  iconsax: ^0.0.8

  # Font
  google_fonts: ^6.2.1
  
  cupertino_icons: ^1.0.8

  # State Management
  get: ^4.6.6
  get_storage: ^2.1.1

  #---------------- ./ PACKAGES END ------------------#

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  
  
  
  
  flutter_lints: ^4.0.0





flutter:
  uses-material-design: true

  #---------------- ./ LOCAL ASSETS ------------------#
  assets:
    - assets/logos/
    - assets/icons/
    - assets/images/

  #---------------- ./ LOCAL FONTS ------------------#
#  fonts:
#    -

  
  
  
